blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/lelorinel/codebeacon/discussions
    about: Ask questions and discuss ideas here.
  - name: Security
    url: https://github.com/lelorinel/codebeacon/security/policy
    about: Report security vulnerabilities here.
